apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-api
  namespace: secure-apps
  labels:
    app: secure-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-api
  template:
    metadata:
      labels:
        app: secure-api
    spec:
      containers:
        - name: secure-api
          image: ghcr.io/toyinogun/secure-api:6ef498a922012c6db1c7aac4f999a82720085ac2
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
