apiVersion: v1
kind: Service
metadata:
  name: secure-api
  namespace: secure-apps
  labels:
    app: secure-api
spec:
  selector:
    app: secure-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
